$(document).ready(function(){     
    $("#minecraft").hide();
    $("#terraria").hide();
    $("#rust").hide();
    $("#7daystodie").hide();
    $("#mumble").hide();
    $("#factorio").hide();
    $("#ark").hide();

    $("#mvan").hide();
    $("#mspi").hide();
    $("#pspi").hide();
    $("#template-minecraft").hide();
    $("#forg").hide();
    $("#cusj").hide();
    $("#template-taupe").hide();
    $("#template-lg").hide();

    $("#tvan").hide();
    $("#tmod").hide();
    $("#tsho").hide();

    
    $("#b1").click(function(){
        $("#minecraft").show();
        $("#terraria").hide();
        $("#rust").hide();
        $("#7daystodie").hide();
        $("#mumble").hide();
        $("#factorio").hide();
        $("#ark").hide();
    });
    $("#b2").click(function(){
        $("#minecraft").hide();
        $("#terraria").show();
        $("#rust").hide();
        $("#7daystodie").hide();
        $("#mumble").hide();
        $("#factorio").hide();
        $("#ark").hide();
    });
    $("#b3").click(function(){
        $("#minecraft").hide();
        $("#terraria").hide();
        $("#rust").show();
        $("#7daystodie").hide();
        $("#mumble").hide();
        $("#factorio").hide();
        $("#ark").hide();
    });
    $("#b4").click(function(){
        $("#minecraft").hide();
        $("#terraria").hide();
        $("#rust").hide();
        $("#7daystodie").show();
        $("#mumble").hide();
        $("#factorio").hide();
        $("#ark").hide();
    });
    $("#b5").click(function(){
        $("#minecraft").hide();
        $("#terraria").hide();
        $("#rust").hide();
        $("#7daystodie").hide();
        $("#mumble").show();
        $("#factorio").hide();
        $("#ark").hide();
    });
    $("#b6").click(function(){
        $("#minecraft").hide();
        $("#terraria").hide();
        $("#rust").hide();
        $("#7daystodie").hide();
        $("#mumble").hide();
        $("#factorio").show();
        $("#ark").hide();
    });    
    $("#b7").click(function(){
        $("#minecraft").hide();
        $("#terraria").hide();
        $("#rust").hide();
        $("#7daystodie").hide();
        $("#mumble").hide();
        $("#factorio").hide();
        $("#ark").show();
    });
    $("#bm1").click(function(){
        $("#mvan").show();
        $("#mspi").hide();
        $("#pspi").hide();
        $("#template-minecraft").hide();
        $("#forg").hide();
        $("#cusj").hide();
    });
    $("#bm2").click(function(){
        $("#mvan").hide();
        $("#mspi").show();
        $("#pspi").hide();
        $("#template-minecraft").hide();
        $("#forg").hide();
        $("#cusj").hide();
    });
    $("#bm3").click(function(){
        $("#mvan").hide();
        $("#mspi").hide();
        $("#pspi").show();
        $("#template-minecraft").hide();
        $("#forg").hide();
        $("#cusj").hide();
    });
    $("#bm4").click(function(){
        $("#mvan").hide();
        $("#mspi").hide();
        $("#pspi").hide();
        $("#template-minecraft").show();
        $("#forg").hide();
        $("#cusj").hide();
    });
    $("#bm5").click(function(){
        $("#mvan").hide();
        $("#mspi").hide();
        $("#pspi").hide();
        $("#template-minecraft").hide();
        $("#forg").show();
        $("#cusj").hide();
    });
    $("#bm6").click(function(){
        $("#mvan").hide();
        $("#mspi").hide();
        $("#pspi").hide();
        $("#template-minecraft").hide();
        $("#forg").hide();
        $("#cusj").show();
    });
    $("#bt1").click(function(){
        $("#tvan").show();
        $("#tmod").hide();
        $("#tsho").hide();
    });
    $("#bt2").click(function(){
        $("#tvan").hide();
        $("#tmod").show();
        $("#tsho").hide();
    });
    $("#bt3").click(function(){
        $("#tvan").hide();
        $("#tmod").hide();
        $("#tsho").show();
    });
    $("#btm1").click(function(){
        $("#template-taupe").show();
        $("#template-lg").hide();
    });
    $("#btm2").click(function(){
        $("#template-taupe").hide();
        $("#template-lg").show();
    });
});